### ISSUE TITLE
Full Mode

### ISSUE THREAD

**Issue by half-drop** [MicrocontrollersDev/Simple-Block-Overlay#1]
Could you please add a full mode like https://www.youtube.com/watch?app=desktop&v=FiiJO-BpxGo 1:53, thanks!
![image](https://github.com/MicrocontrollersDev/Simple-Block-Overlay/assets/39797906/8d3b77c9-ec45-4d0c-9841-390fb5f7a107)

**Comment by MicrocontrollersDev** [comment]
This is not as simple to do and would require me to create my own rendering, and I'm not very good at rendering. It's something I'd like to look into but I don't have much time.

**Comment by SzczurekYT** [comment]
> This is not as simple to do and would require me to create my own rendering, and I'm not very good at rendering. It's something I'd like to look into but I don't have much time.

I might be interested in helping, if I will find some time I will try to look into it.
I too don't know much about rendering, but I have done some simple things and rendering few faces is not that hard :)

**Comment by MicrocontrollersDev** [comment]
> I might be interested in helping, if I will find some time I will try to look into it. I too don't know much about rendering, but I have done some simple things and rendering few faces is not that hard :)

If you are able to, that would be awesome!

**Comment by SzczurekYT** [comment]
👀

![image](https://github.com/MicrocontrollersDev/Simple-Block-Overlay/assets/67533827/e4ecdf29-cc6d-4bec-80db-949a89706c31)
(it's not working fully yet, but it's coming 😄)

**Comment by MicrocontrollersDev** [comment]
Now available in 1.3.0!
