### ISSUE TITLE
The 1.3.0 for 1.20 version was compiled with java 21 (UnsupportedClassVersionError)

### ISSUE THREAD

**Issue by SzczurekYT** [MicrocontrollersDev/Simple-Block-Overlay#4]
The [1.3.0](https://modrinth.com/mod/simple-block-overlay/version/1.3.0) version for 1.20.0-1.20.6 was compiled with java 21 while minecraft 1.20.x is meant to be run on java 17.
This results in UnsupportedClassVersionError being thrown trying to start minecraft.

**Comment by MicrocontrollersDev** [comment]
WHOOPS

**Comment by MicrocontrollersDev** [comment]
fixed in 1.3.1, now uses 1.20.4 to build instead of 1.20.6 (why is mojang bumping java requirements in a patch version semver is dead)
