### ISSUE TITLE
Mod causes "Resource reload fail"

### ISSUE THREAD

**Issue by benben5000** [MicrocontrollersDev/Simple-Block-Overlay#5]
Whenever this mod is enabled the instance in unable to load any resources for the game

**Comment by MicrocontrollersDev** [comment]
What mc versions and other mods? Also fabric or quilt?

**Comment by Hi-ImKyle** [comment]
Same error here. Spent some time disabling and enabling mods and found it seems to be [Highlight](https://modrinth.com/mod/highlight). At least for me anyway. 

Loading resources still works, just with Highlight enabled it triggers the "Resource reload failed" toast in the top right which also causes the game drop all the way back to the main menu, including when I am in a server or a single player world.

**Comment by MicrocontrollersDev** [comment]
this has temporarily been fixed in 1.4.2 as i have removed compat support for Highlight. I will look into it again in the future
