### ISSUE TITLE
chinese language help

### ISSUE THREAD

**Issue by LuoliiQaQ** [MicrocontrollersDev/Simple-Block-Overlay#8]
I want to know where to set the language? I want to set it to Chinese

**Comment by MicrocontrollersDev** [comment]
hello, it should automatically set when you change your minecraft language to chinese simplified

**Comment by MicrocontrollersDev** [comment]
working for me
![image](https://github.com/user-attachments/assets/df0f4d9a-e920-40dd-b3b2-7f5dc37d88f3)
![image](https://github.com/user-attachments/assets/b6004b20-dd59-4c68-8d06-cdd34f235949)

**Comment by LuoliiQaQ** [comment]
Oh, that's what I did. I'm fine. Thank you so much

**Comment by LuoliiQaQ** [comment]
Thank you. I set it up
